spring:
    profiles:
        active: sit
acme:
    list:
    -   name: my name
        description: my description
    -   name: another name
        description: another description
    map:
        key1:
            name: my name 1
            description: my description 1
---
spring:
    profiles: dev
acme:
    list:
    -   name: my another name
    map:
        key1:
            name: dev name 1
        key2:
            name: dev name 2
            description: dev description 2
---
jasypt:
    encryptor:
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
    profiles: sit
    redis:
        timeout: 6000
        # password: abcd1234
        # sentinel:
            # master: mymaster
            # nodes: 127.0.0.1:26380,127.0.0.1:26381,127.0.0.1:26382
        cluster:
            max-redirects: 4
            nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004
        lettuce:
            pool:
                max-active: 100
                max-idle: 100
                min-idle: 10
                max-wait: 1000
    mail:
        host: smtp.163.com
        port: 994 # SSL 465/994 # 普通 25
        username: ENC(uBuEdIp9x9Qd32QufRXEQoMv5/wfcI0nISwCEYi/VeI=)
        password: ENC(GD/7gWvwjmdenkCN/sF6ZdALA519IIBiXGx2KozsVx8=)
        properties:
            "[mail.debug]": true
            "[mail.smtp.auth]": true
            "[mail.smtp.ssl.enable]": true
            "[mail.smtp.starttls.enable]": true
            "[mail.smtp.starttls.required]": true
            "[mail.smtp.timeout]": 30000
            "[mail.smtp.writetimeout]": 60000
            "[mail.smtp.connectiontimeout]": 30000
    freemarker:
        suffix: .ftlh # 默认配置
        template-loader-path: classpath:/templates/freemarker
    thymeleaf:
        mode: HTML
        suffix: .html
        prefix: classpath:/templates/thymeleaf/
    jms:
        pub-sub-domain: true
    activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin
        packages:
            trust-all: true
        pool:
            enabled: true
            idle-timeout: 60000
            max-connections: 10 # JMS池中最大连接数
            max-sessions-per-connection: 100 # JMS池中每个连接的最大会话数
        queue-names:
            smsQueue: sms-queue
            mailQueue: mail-queue
        topic-names:
            smsTopic: sms-topic
            mailTopic: mail-topic
acme:
    list:
    -   name: my sit name1
        description: my sit description1
    -   name: my sit name2
        description: my sit description2
    map:
        key1:
            name: sit name 1
        key2:
            name: sit name 2
            description: sit description 2
business:
    report:
        fine_signature_key: hnlcbReportSing
        light-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneLightExport.cpt&format=excel&extype=simple
        light-pho-project-sum-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=phoprojectSum.cpt
        light-pho-project-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=phoproject.cpt
        milestone-plan-excute-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCount2019.cpt
        milestone-accu-excute-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExcuteCount2019.cpt
        planning-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExport.cpt&format=excel&extype=simple
        planadjust-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanQuantityAdjustExport.cpt&format=excel&extype=simple
        actualing-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExport.cpt&format=excel&extype=simple
        batch-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneBatchExport.cpt&format=excel&extype=simple
        project-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneProjectExport.cpt&format=excel&extype=simple
        milestone-batch-node-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneBatchNodeAuditExport.cpt&format=excel&extype=simple
        milestone-batch-audit-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneBatchNodeAuditAuthExport.cpt&format=excel&extype=simple
        milestone-project-node-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneProjectNodeAuditExport.cpt&format=excel&extype=simple
        milestone-material-node-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialNodeAuditExport.cpt&format=excel&extype=simple
        project-complete-report-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExcuteCountFinish2019.cpt
        project-un-complete-report-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExcuteCountUnfinish2019.cpt
        milestone-month-plan-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountMonth.cpt
        milestone-rate-plan-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanRateExcuteCount.cpt
        report-server: http://127.0.0.1:8280/WebReport/ReportServer
        milestone-node-plan-adjust-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneNodePlanAdjustExport.cpt&format=excel&extype=simple
        milestone-node-plan-adjust-audit-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneNodePlanAdjustAuditExport.cpt&format=excel&extype=simple
        jobs-match-frame-export-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneFrameAgreement.cpt&format=excel&extype=simple
        milestone-construct-match-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneConstructMatchResult.cpt
        milestone-construct-unit-match-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneConstructUnitMatchResult.cpt
        milestone-village-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneVillageExport.cpt&format=excel&extype=simple
        milestone-defect-type-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneDefectTypeExport.cpt&format=excel&extype=simple
        milestone-material-type-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialTypeExport.cpt&format=excel&extype=simple
        material-contract-problem-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialContractProblemInfo.cpt&format=excel&extype=simple
        material-contract-problem-audit-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialContractProblemInfoAudit.cpt&format=excel&extype=simple
        material-problem-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialProblemInfo.cpt&format=excel&extype=simple
        material-problem-audit-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialProblemInfoAudit.cpt&format=excel&extype=simple
        material-quality-problem-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialQualityProblem.cpt
        material-summary-city-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneCityMaterialSummary.cpt
        material-summary-country-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneCountryMaterialSummary.cpt
        material-summary-detail-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneMaterialContractFulfillmentProblem.cpt
        milestone-app-accu-excute-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePCAndAPPAccuExcuteCount.cpt
        milestone-plan-excute-count-batch-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountBatchExport.cpt&format=excel&extype=simple
        milestone-plan-excute-count-project-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountProjectExport.cpt&format=excel&extype=simple
        milestone-accu-excute-count-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExcuteCountExport.cpt&format=excel&extype=simple
        milestone-accu-excute-count-unfinish-export-uri: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneAccuExcuteCountUnfinishExport.cpt&format=excel&extype=simple
        example-project-export-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=ExampleProjectExport.cpt&format=excel&extype=simple
        milestone-example-project-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestoneExampleProject.cpt
        milestone-complete-country-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountNewCountry.cpt
        milestone-complete-city-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountNewCity.cpt
        milestone-complete-powerhouse-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=MilestonePlanExcuteCountNewPowerhouse.cpt
        milestone-user-problem-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=UseProblemExport.cpt&format=excel&extype=simple
        pmstrans-project-url: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=PmsTransProjectExport.cpt&format=excel&extype=simple
        milestone-complete-country-url-copy: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=copy/MilestonePlanExcuteCountNewCountry.cpt
        milestone-complete-city-url-copy: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=copy/MilestonePlanExcuteCountNewCity.cpt
        milestone-complete-powerhouse-url-copy: http://127.0.0.1:8280/WebReport/ReportServer?reportlet=copy/MilestonePlanExcuteCountNewPowerhouse.cpt